// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRdPDeog8Dk8UBYpbMsXlJGVh27FRRyBE',
    appId: '1:247198476840:web:42b9110cc196ad940da31d',
    messagingSenderId: '247198476840',
    projectId: 'e-commerce-projects-d0287',
    authDomain: 'e-commerce-projects-d0287.firebaseapp.com',
    storageBucket: 'e-commerce-projects-d0287.firebasestorage.app',
    measurementId: 'G-EDKF79DPVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6V_U1jre8HJDg7iDFS8lKB25U9v9dXN4',
    appId: '1:247198476840:android:97bc053a539ca8b50da31d',
    messagingSenderId: '247198476840',
    projectId: 'e-commerce-projects-d0287',
    storageBucket: 'e-commerce-projects-d0287.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwdqeDtFOYqm4hG2GnOoWQv5YFzvpcIGk',
    appId: '1:247198476840:ios:b5b56eedd1a673990da31d',
    messagingSenderId: '247198476840',
    projectId: 'e-commerce-projects-d0287',
    storageBucket: 'e-commerce-projects-d0287.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
