// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzvqkjfuChtHIEcx_u7JXR5jcxHwjDE_0',
    appId: '1:445543926352:web:fa923f5f248988fa86df55',
    messagingSenderId: '445543926352',
    projectId: 'my-ecom-project01-9486a',
    authDomain: 'my-ecom-project01-9486a.firebaseapp.com',
    storageBucket: 'my-ecom-project01-9486a.appspot.com',
    measurementId: 'G-02W79Z5DN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2BpgKo7bowkGvZi4ukS5cvTwmSW_jyrU',
    appId: '1:445543926352:android:a11d4744394f39d886df55',
    messagingSenderId: '445543926352',
    projectId: 'my-ecom-project01-9486a',
    storageBucket: 'my-ecom-project01-9486a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA5OEip8vPr2u_nslp1_U6f8Wg4_neHGA',
    appId: '1:445543926352:ios:ab562a78c3bf655f86df55',
    messagingSenderId: '445543926352',
    projectId: 'my-ecom-project01-9486a',
    storageBucket: 'my-ecom-project01-9486a.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

}